### ISSUE TITLE
Fix my name

### ISSUE THREAD

**Issue by cdqwertz** [rubenwardy/VoxelLegends#5]
There is a mistake in README.md
`cd5 (for creating rpgtest)`
Change that to 
`cd2 (@cdqwertz - for creating rpgtest)`
please.

**Comment by rubenwardy** [comment]
Oops, Sorry! I guessed as I couldn't remember, and was planning to check but forgot.

**Comment by rubenwardy** [comment]
When are you online, @cdqwertz? What is your timezone? If you could come into #minetest @ irc.freenode.net I'd be grateful, I'd like to discuss your plans for the quest and story mods.
